title: Melon Blog

name: Melon

description: 一些日常问题积累,记录一下

anchor: melon

cayman-blog:
      date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman

encoding: UTF-8

timezone: Asia/Shanghai

exclude: ['.gitignore', 'CHANGELOG.md', 'Gemfile', 'Gemfile.lock', 'LICENSE.md', 'README.md']
